# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - release
  - nightly
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false
# uncomment the following lines to override the default test script
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - TESTCMD="xvfb-run julia"
  - if [[ "$(uname)" != "Linux" ]]; then TESTCMD="julia"; fi
  - $TESTCMD -e 'Pkg.clone(pwd()); Pkg.build("InspectDR"); Pkg.test("InspectDR"; coverage=true)'
